### ISSUE TITLE
Compatibility with Symfony 3.1

### ISSUE THREAD

**Issue by thomasez** [schmittjoh/JMSSecurityExtraBundle#207]
Seems like there has been a change not mentioned in the UPGRADE-3.1 fil for Symfony regarding the DebugAccessDecisionManager. I get this:

 [Symfony\Component\Debug\Exception\ContextErrorException] Catchable Fatal Error: Argument 1 passed to Symfony\Component\Security\Core\Authorization\DebugAccessDecisionManager::__construct() must be an instance of Symfony\Component\Security\Core\Authorization\AccessDecisionManager, instance of JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager given, called in app/cache/dev/appDevDebugProjectContainer.php on line 4033 

(Stack trace can be provided)

Seems like someone found this in the serializer bundle aswell:
https://github.com/schmittjoh/JMSSerializerBundle/issues/518

(But it refers to the security bundle there, so it may be the same issue as this.)

Works witrh 3.0.6 so this is something new.

**Comment by thomasez** [comment]
https://github.com/symfony/symfony/pull/18934/files#r65385219  fixes this issue. (Thanks @stof and @javiereguiluz) 

So no I've hit the next bump:

ReflectionException in DebugAccessDecisionManager.php line 37: Property JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager::$strategy does not exist

    in DebugAccessDecisionManager.php line 37
    at ReflectionProperty->__construct(object(RememberingAccessDecisionManager), 'strategy') in DebugAccessDecisionManager.php line 37
    at DebugAccessDecisionManager->__construct(object(RememberingAccessDecisionManager)) in appDevDebugProjectContainer.php line 4003
    at appDevDebugProjectContainer->getSecurity_Access_DecisionManagerService() in Container.php line 275

Cut & paste of the missing code from src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php (setVoters, GetStrategy and getVoters and the part in the constructor) did that trick.

At least I get through and I can look at the security page in the debugger. It looks ok.

(PR wanted? it's a very simple cut&paste and may not even be correct other than getting rid of exceptions..)

**Comment by HeahDude** [comment]
Can be closed https://github.com/symfony/symfony/pull/18934 has been merged now.

**Comment by francoispluchino** [comment]
Sorry, but this issue is not solved.

The `JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager` is not fully compatible with Symfony 3.1 in debug.

With the [DebugAccessDecisionManager](https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php) class, the Access Decision Manager must be an instance of `Symfony\Component\Security\Core\Authorization\AccessDecisionManager` to [set the voters](https://github.com/symfony/symfony/blob/3.1/src/Symfony/Component/Security/Core/Authorization/DebugAccessDecisionManager.php#L65).

The result is that there is no longer a single voter in the Access Decision Manager. Consequence : the value of `Symfony\Component\Security\Core\Authorization\AccessDecisionManagerInterface::decide()` method is always `false`.


@Ener-Getick Please, reopen this issue.

**Comment by HeahDude** [comment]
@francoispluchino see https://github.com/symfony/symfony/pull/19272

**Comment by francoispluchino** [comment]
@HeahDude Alas, your proposal is useless for the moment, because the `JMS\SecurityExtraBundle\Security\Authorization\RememberingAccessDecisionManager` class doesn't have the `setVoters` method.

`RememberingAccessDecisionManager` class must also be changed.

**Comment by TheCelavi** [comment]
What is the purpose of having RememberingAccessDecisionManager?

I see that only difference is in method "getLastDecisionCall" and having a result of last made decision, but I do not see its usage anywhere else in bundle.

Is this class necessary?

BTW, this bug can be fixed by inheritance, currently, RememberingAccessDecisionManager decorates Symfony\Component\Security\Core\Authorization\AccessDecisionManager, and in dev mode, DebugAccessDecisionManager decorates RememberingAccessDecisionManager, which is fine, but on line 65 expects instance of AccessDecisionManager to set voters.

So, instead of RememberingAccessDecisionManager decorating AccessDecisionManager, it should inherit it, and in compiler pass, it should change class of security.access.decision_manager and everything could work.

Of course, "getLastDecisionCall" should be supported, and that can be achieved easily. 

I can fix this properly, I just need info is this really required, since I do not see that is being used anywhere...

I thought that RememberingAccessDecisionManager caches all decisions, so two successive same questions to method:

    public function decide(TokenInterface $token, array $attributes, $object = null) 

would be executed faster, once by asking voters, and second one would just consult the cache....

Anyone?

**Comment by TheCelavi** [comment]
This is trivial issue, fixable, does not require too much time, I can do it today, just need answer to previous question, please... thanks.

**Comment by schmittjoh** [comment]
The class can be used in your AccessDeniedHandler for example to figure out why access was denied and redirect accordingly to rectify the problem if possible.

We could probably extend, from an OO point, it will make it impossible or very hard to inject any other implementation of ADM. Can we just add the missing method to the RememberingADM? I think that works fine too, no?

**Comment by TheCelavi** [comment]
1. "The class can be used" => Ok, understood now, thank you. I would like to add a comment to this method signature, or to document it, since it was not clear at the first sight why should I need that. Idea is valid, purpose is valid.

2. See https://github.com/symfony/security-core/blob/master/Authorization/DebugAccessDecisionManager.php, line no 63.

Previously, it was:

    public function setVoters(array $voters)
    {
        if (!$this->manager instanceof AccessDecisionManager) {
            return;
        }

        $this->voters = $voters;
        $this->manager->setVoters($voters);
    }

That is why I proposed inheritance. As you can see now, from current master-dev branch, they just check if method "setVoters" exists -> which is good, it is sufficient enough to add "setVoters" method to RememberingADM, this would be the fix then:


    public function setVoters(array $voters)
    {
        if (!method_exists($this->delegate, 'setVoters')) {
            throw new \RuntimeException(sprintf('Decorated implementation of "%s", instance of class "%s" does not have "setVoters" which is required for development environment.', AccessDecisionManagerInterface::class, get_class($this->delegate)));
        }

        $this->delegate->setVoters($voters);
    }

**BUT!!!** That will fix the issue when using 'master-dev' branch, however, latest tag symfony/security is 3.1.2 and when using that package version (or bellow), adding "setVoters" method to RememberingADM is futile, see: https://github.com/symfony/security/blob/v3.1.2/Core/Authorization/DebugAccessDecisionManager.php

So... what say you? We just add "setVoters" method, and we use "master-dev" version of "symfony/security" until tag 3.1.3 (or above) is added?

**Comment by schmittjoh** [comment]
Tagging should just be a matter of time, so let's go with just adding the method. This still allows developers to decide how the objects are composed (vs. fixed inheritance).

**Comment by HeahDude** [comment]
Tagging is matter of days ;)

**Comment by dovys** [comment]
Hey, could you tag it? We just moved to symfony 3.1.5 and have an issue with voters being not set in the AccessDecisionManager
