### ISSUE TITLE
Work together with Symfony ParamConverter

### ISSUE THREAD

**Issue by Fludimir** [schmittjoh/JMSSecurityExtraBundle#71]
Not sure where to report better, decided here.

When using @Secure annotation together with @ParamConverter http://symfony.com/doc/current/bundles/SensioFrameworkExtraBundle/annotations/converters.html - ParamConverter is working before secure check, and even if token has no access doctrine will execute query for requested object. This doesn't happens with standard symfony security. Some other events may also be dispatched before security checks

**Comment by georgevanvliet** [comment]
I've must say that I've run into this one a few times as well. We throw a blanket 404 response for 403 errors, in order to prevent the guessing of certain identifiers through enumeration (yes, always try to use uuids, but not always possible).
On endpoints that require you to be logged in however, the above behavior puts me in trouble.

Logged in:
* Try to access something I am not allowed to (AccessDeniedHttpException) --> converted to 404
* Try to access something that does not exist --> 404

The above works fine in preventing enumeration when logged in.

Now consider when I am **not** logged in and try to access the endpoint:
* Try to access something that does not exist --> 404
* Try to access something that does exist --> 401

Now I would expect to *always* receive a 401, since it is required I am logged in. Otherwise I have to throw a blanket response 404 now, for 401s. Which I do not find appropriate.

But I am guessing the solution is to use @PreAuthorize.
